language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
  - rbx-2
before_install:
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev gobject-introspection gir1.2-gtk-3.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake test"
