language: ruby

dist: xenial

services:
  - xvfb

before_install:
  - sudo apt-get update
  # Provides libgirepository-1.0.so.1
  - sudo apt-get install libgirepository-1.0-1
  # Provides Pango-1.0.typelib
  - sudo apt-get install gir1.2-pango-1.0
  # Provides Gdk-3.0.typelib
  - sudo apt-get install gir1.2-gtk-3.0

cache:
  bundler: true

rvm:
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.2
  - ruby-head
  - ruby-head-clang
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
    - rvm: jruby-head

branches:
  only:
    - master
