# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gir_ffi-pango"
  s.version = "0.0.2"

  s.summary = "GirFFI-based bindings for Pango"
  s.description = "Bindings for Pango generated by GirFFI, with an eclectic set of overrides."

  s.authors = ["Matijs van Zuijlen"]
  s.email = ["matijs@matijs.net"]
  s.homepage = "http://www.github.com/mvz/gir_ffi-pango"

  s.files = Dir['{lib,test}/**/*.rb', "README.md", "Rakefile", "COPYING.LIB"]
  s.test_files = Dir['test/**/*.rb']

  s.add_runtime_dependency(%q<gir_ffi>, ["~> 0.4.0"])
  s.add_development_dependency('minitest', ["~> 2.11"])
  s.add_development_dependency('rake', ["~> 0.9.2"])

  s.require_paths = ["lib"]
end
